name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test (stable)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose
      - name: Test VPS
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --nocapture
      - name: Github Release
        uses: elgohr/Github-Release-Action@v3.1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          args: Release
