name: RELEASE

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --verbose
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: vps.linux
          path: target/release/vps
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "vps.linux"
          token: ${{ secrets.GITHUB_TOKEN }}
